package com.myspace.pocservicemanifesto;


import com.myspace.pocservicemanifesto.Order;
import com.myspace.pocservicemanifesto.OrderLine;
import java.time.OffsetDateTime;
// declare any global variables here
// TODO:add a proper logging layer
// import org.apache.log4j.Logger
// global Logger LOGGER;

rule "Setting default values on Order"
	dialect "mvel"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
	    order : Order( )
	then
	    System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
	    order.setRequestedDate(OffsetDateTime.parse(order.getRequestedDateStr()));
	    order.setOrderDate(OffsetDateTime.parse(order.getOrderDateStr()));
	    order.setMessage("OK");
	    order.setMessageType("INFO");
	    order.setDateDiff(order.getRequestedDate().compareTo(order.getOrderDate()));
	    System.out.println("date compare : [" + order.getDateDiff() + "]");
end 

rule "Setting default values on OrderLine"
	dialect "mvel"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
	    orderLine : OrderLine( )
	then
	    System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
	    
end