package com.myspace.pocservicemanifesto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderAux implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderAux() {
    }




}